[package]
name = "simple-locale"
version = "0.1.0"
authors = ["Simon Johnston <johnstonskj@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.3.0"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"