#!/usr/bin/env bash

case $(uname) in
  Darwin)
    if [[ $(command -v llvm-config) ]] ; then
      INCLUDE="$(xcode-select -p)/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include"
      BIND_HEADERS=langinfo,localcharset,locale,xlocale
      MODULE=macos
      else
        echo "llvm not installed, or not on the path"
        echo ">> brew install llvm"
        echo ">> PATH=\$PATH:/usr/local/opt/llvm/bin"
        exit 2
      fi
    ;;
  Linux)
    INCLUDE="/usr/include"
    BIND_HEADERS=langinfo,localcharset,locale,xlocale
    MODULE=linux
    ;;
  *)
    echo "Unsupported O/S"
    exit 1
    ;;
esac

MODULES=""
for HEADER in ${BIND_HEADERS//,/ }
do
  if [[ -f "$INCLUDE/$HEADER.h" ]] ; then
    echo "generating bindings for $INCLUDE/$HEADER.h into src/ffi/$MODULE/$HEADER.rs"
    bindgen --verbose $INCLUDE/$HEADER.h --output src/ffi/$MODULE/$HEADER.rs
    git add src/ffi/$MODULE/$HEADER.rs
    MODULES=$(printf "%s\n#[allow(non_snake_case, non_camel_case_types, dead_code, unused_variables)]\npub mod %s;\n" "$MODULES" $HEADER)
  else
    echo "header file $HEADER.h does not exist in $INCLUDE"
  fi
done

VERSION_FILE="src/ffi/$MODULE/mod.rs"

echo "writing module file in $VERSION_FILE"

cat <<EOF > "$VERSION_FILE"
/* automatically generated by create-bindings */
/* generated on $(date), */
/*   for $(uname -s), release $(uname -r) */
$MODULES
EOF
git add $VERSION_FILE