/* automatically generated by create-bindings */
/* generated on Wed 21 Aug 2019 07:59:25 PM PDT, */
/*   for Linux, release 5.0.0-27-generic */

#[allow(
    non_snake_case,
    non_camel_case_types,
    non_upper_case_globals,
    dead_code,
    unused_variables
)]
pub mod langinfo;
#[allow(
    non_snake_case,
    non_camel_case_types,
    non_upper_case_globals,
    dead_code,
    unused_variables
)]
pub mod locale;
