/* automatically generated by create-bindings */
/* generated on Wed Jul 31 08:53:36 PDT 2019 */

pub const PLATFORM_NAME: &'static str = "Darwin";

pub const PLATFORM_RELEASE: &'static str = "18.7.0";

#[allow(non_snake_case, non_camel_case_types, dead_code, unused_variables)]
pub mod langinfo;
#[allow(non_snake_case, non_camel_case_types, dead_code, unused_variables)]
pub mod localcharset;
#[allow(non_snake_case, non_camel_case_types, dead_code, unused_variables)]
pub mod locale;
#[allow(non_snake_case, non_camel_case_types, dead_code, unused_variables)]
pub mod xlocale;
