/* automatically generated by create-bindings */
/* generated on Wed Jul 31 08:42:25 PDT 2019 */

pub const PLATFORM_NAME: &'static str = "Darwin";

pub const PLATFORM_RELEASE: &'static str = "18.7.0";

pub mod langinfo;
pub mod localcharset;
pub mod locale;
pub mod xlocale;
